# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-17 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitydemanded', models.IntegerField(default=0)),
                ('quantitysupplied', models.IntegerField(default=0)),
                ('quantityname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Product')),
            ],
        ),
    ]
