# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-21 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='Department',
            field=models.TextField(default=''),
        ),
    ]
